version: "3.8"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=d67kqbq6hnmd66
      - POSTGRES_USER=igzqcxmdmlmblc
      - POSTGRES_PASSWORD=170311d87ffbd680ee89a6ae9edb811bc438720b1f4892c46ba2438f0cf5bfc4
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=d67kqbq6hnmd66
      - POSTGRES_USER=igzqcxmdmlmblc
      - POSTGRES_PASSWORD=170311d87ffbd680ee89a6ae9edb811bc438720b1f4892c46ba2438f0cf5bfc4
    depends_on:
      - db